"""fix_registros_table

Revision ID: 84be38e0c8ca
Revises: 9616937de794
Create Date: 2025-11-29 19:35:26.429544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '84be38e0c8ca'
down_revision: Union[str, None] = '9616937de794'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo_evento', sa.Enum('RESERVA', 'ANUNCIO', 'MULTA', 'PAGO', 'EDICION', 'ELIMINACION', 'CREACION', 'OTRO', name='tipoevento'), nullable=False),
    sa.Column('detalle', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=True),
    sa.Column('condominio_id', sa.Integer(), nullable=True),
    sa.Column('datos_adicionales', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['condominio_id'], ['condominios.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registros')
    # ### end Alembic commands ###