# coding: utf-8

"""
    Casitas Teto API

    API para Sistema de Gestión de Condominios

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from app.apis.anuncios_api import router as AnunciosApiRouter
from app.apis.autenticacin_api import router as AutenticacinApiRouter
from app.apis.condominios_api import router as CondominiosApiRouter
from app.apis.espacios_comunes_api import router as EspaciosComunesApiRouter
from app.apis.gastos_comunes_api import router as GastosComunesApiRouter
from app.apis.multas_api import router as MultasApiRouter
from app.apis.pagos_api import router as PagosApiRouter
from app.apis.residentes_api import router as ResidentesApiRouter
from app.apis.usuarios_api import router as UsuariosApiRouter

app = FastAPI(
    title="Casitas Teto API",
    description="API para Sistema de Gestión de Condominios",
    version="1.0.0",
)

app.include_router(AnunciosApiRouter)
app.include_router(AutenticacinApiRouter)
app.include_router(CondominiosApiRouter)
app.include_router(EspaciosComunesApiRouter)
app.include_router(GastosComunesApiRouter)
app.include_router(MultasApiRouter)
app.include_router(PagosApiRouter)
app.include_router(ResidentesApiRouter)
app.include_router(UsuariosApiRouter)
