# coding: utf-8

"""
    Casitas Teto API

    API para Sistema de Gestión de Condominios

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import date, datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class Reserva(BaseModel):
    """
    Reserva
    """ # noqa: E501
    id: Optional[StrictInt] = None
    espacio_comun_id: Optional[StrictInt] = Field(default=None, alias="espacioComunId")
    residente_id: Optional[StrictInt] = Field(default=None, alias="residenteId")
    fecha_reserva: Optional[date] = Field(default=None, alias="fechaReserva")
    hora_inicio: Optional[StrictStr] = Field(default=None, alias="horaInicio")
    hora_fin: Optional[StrictStr] = Field(default=None, alias="horaFin")
    estado: Optional[StrictStr] = None
    monto_pago: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="montoPago")
    pago_id: Optional[StrictInt] = Field(default=None, alias="pagoId")
    observaciones: Optional[StrictStr] = None
    fecha_creacion: Optional[datetime] = Field(default=None, alias="fechaCreacion")
    __properties: ClassVar[List[str]] = ["id", "espacioComunId", "residenteId", "fechaReserva", "horaInicio", "horaFin", "estado", "montoPago", "pagoId", "observaciones", "fechaCreacion"]

    @field_validator('estado')
    def estado_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('PENDIENTE_PAGO', 'CONFIRMADA', 'CANCELADA', 'COMPLETADA',):
            raise ValueError("must be one of enum values ('PENDIENTE_PAGO', 'CONFIRMADA', 'CANCELADA', 'COMPLETADA')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Reserva from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if monto_pago (nullable) is None
        # and model_fields_set contains the field
        if self.monto_pago is None and "monto_pago" in self.model_fields_set:
            _dict['montoPago'] = None

        # set to None if pago_id (nullable) is None
        # and model_fields_set contains the field
        if self.pago_id is None and "pago_id" in self.model_fields_set:
            _dict['pagoId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of Reserva from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "espacioComunId": obj.get("espacioComunId"),
            "residenteId": obj.get("residenteId"),
            "fechaReserva": obj.get("fechaReserva"),
            "horaInicio": obj.get("horaInicio"),
            "horaFin": obj.get("horaFin"),
            "estado": obj.get("estado"),
            "montoPago": obj.get("montoPago"),
            "pagoId": obj.get("pagoId"),
            "observaciones": obj.get("observaciones"),
            "fechaCreacion": obj.get("fechaCreacion")
        })
        return _obj


